### ISSUE TITLE
Running the action in a container fails 

### ISSUE THREAD

**Issue by rajbos** [runforesight/workflow-telemetry-action#44]
Any chance this action could run inside of a container? I tried to run this inside of a Ubuntu 22.04 container and it [fails](https://github.com/rob-demo/TailwindTraders-Website-LIL/actions/runs/5701386946/job/15452053916). I love the information it returns and that it runs across all types of hosted runners.

At work we use the [actions-runner-controller](https://github.com/actions/actions-runner-controller), which means all runners are hosted inside of containers with docker-in-docker capabilities. I suspect it will fail there as well, but have not tested yet. I would really like to suggest this action to our users for helping them right sizing the runners they use.

**Comment by rwxdash** [comment]
Yes, it's possible to run this in a container. If I recall correctly, you would need to set the privileged mode to true when running it. However, eBPF calls should be available in order to run successfully. Not sure of the exact configuration for a stand-alone container setup, but for the actions-runner-controller we've used the following configuration to make the functionality available. This was for some time ago, so again, I'm not certain if it still works but the idea is the same; make it privileged and make the eBPF syscalls available inside the container.

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ghe-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      repository: oguzhan/dummy
      containers:
        - name: runner
          securityContext:
            privileged: true
          volumeMounts:
            - name: debugfs
              mountPath: /sys/kernel/debug
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
            type: DirectoryOrCreate
```

Also, just an FYI about the current status of Thundra and its products: https://www.catchpoint.com/press-releases/catchpoint-invests-to-advance-api-cloud-functions-and-microservices-monitoring
